import 'package:gymvision/enums.dart';

import '../db/classes/exercise.dart';

class DataHelper {
  static List<Exercise> getDefaultExercises() => [
// shoulders
        Exercise(
          id: 1,
          name: 'DB Shoulder Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 2,
          name: 'Steering Wheel Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 4,
          name: 'DB Lateral Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 5,
          name: 'DB Front Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 6,
          name: 'DB Rear Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 7,
          name: 'Cable Lateral Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 8,
          name: 'Cable Front Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 9,
          name: 'Cable Rear Delt Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 11,
          name: 'Barbell Shoulder Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.barbell,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 12,
          name: 'Plated Shoulder Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 13,
          name: 'Shoulder Press Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.push,
          isDouble: false,
        ),

// chest
        Exercise(
          id: 14,
          name: 'Plated Chest Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 15,
          name: 'Cable Low Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 16,
          name: 'Cable Mid Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 17,
          name: 'Cable High Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 18,
          name: 'DB Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 19,
          name: 'Flat DB Chest Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 20,
          name: 'Incline DB Chest Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 21,
          name: 'Flat Bench Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 22,
          name: 'Incline Bench Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 23,
          name: 'Pectoral Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.push,
          isDouble: false,
        ),

// biceps
        Exercise(
          id: 24,
          name: 'DB Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 25,
          name: 'Seated DB Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 26,
          name: 'Barbell Bicep Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.barbell,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 27,
          name: 'Cable Bar Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 28,
          name: 'Single Cable Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 29,
          name: 'DB Hammer Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 30,
          name: 'Chin Up',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 31,
          name: 'Preacher Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),

// back
        Exercise(
          id: 32,
          name: 'Cable Diverging Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 33,
          name: 'Cable Pullover',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 34,
          name: 'Cable Single Pullover',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 35,
          name: 'Lat Pulldown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 36,
          name: 'Short Grip Lat Pulldown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 37,
          name: 'Seated Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 38,
          name: 'Plated Low Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 39,
          name: 'T Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 40,
          name: 'Bench DB Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 41,
          name: 'Pull up',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 42,
          name: 'Kneeling Cable Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 3,
          name: 'DB Shrug',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back, // moved from shoulders to back
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),

// triceps
        Exercise(
          id: 43,
          name: 'Triceps Pushdown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 44,
          name: 'Single Tricep Pushdown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 45,
          name: 'Cable Triceps Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 46,
          name: 'Single Cable Tricep Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 47,
          name: 'DB Triceps Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 48,
          name: 'Single DB Tricep Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          id: 49,
          name: 'Triceps Dip',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 50,
          name: 'Skull Crushers',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.barbell,
          split: ExerciseSplit.push,
          isDouble: false,
        ),

// core
        Exercise(
          id: 51,
          name: 'Crunch Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 52,
          name: 'Suspended Leg Lifts',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 53,
          name: 'Oblique Lift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.kettlebell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 54,
          name: 'Sit-Ups',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 55,
          name: 'Russian Twists',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 56,
          name: 'Cable Crunch',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),

// hamstrings & glutes
        Exercise(
          id: 57,
          name: 'Cable Abductor Lift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 58,
          name: 'Abductor Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 59,
          name: 'Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 60,
          name: 'Single Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 61,
          name: 'Prone Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 62,
          name: 'Single Prone Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 63,
          name: 'Sumo Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 64,
          name: 'Deadlift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 65,
          name: 'RDL',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 66,
          name: 'DB RDL',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 67,
          name: 'Hip Thrust',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),

// quads & calves
        Exercise(
          id: 68,
          name: 'Hack Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 69,
          name: 'Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 70,
          name: 'Barbell Lunge',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 71,
          name: 'DB Lunge',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 72,
          name: 'Leg Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 73,
          name: 'Calf Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 74,
          name: 'Leg Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 75,
          name: 'Single Leg Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 76,
          name: 'Barbell Calf Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 77,
          name: 'Single Barbell Calf Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 78,
          name: 'DB Calf Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 79,
          name: 'Adductor Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),

// forearms
        Exercise(
          id: 80,
          name: 'DB Wrist Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.forearms,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 81,
          name: 'DB Wrist Rotation',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.forearms,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          id: 82,
          name: 'Cable Wrist Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.forearms,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),

// additions
        Exercise(
          id: 83,
          name: 'Barbell Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 84,
          name: 'Cable Face Pull',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 85,
          name: 'Flat Smiths Bench Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 86,
          name: 'Incline Smiths Bench Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          id: 87,
          name: 'Sissy Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 88,
          name: 'Raised Heel Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          id: 89,
          name: 'Seated Wide Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 90,
          name: 'Single Calf Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          id: 91,
          name: 'Rear Delt Fly Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 92,
          name: 'Standing T Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          id: 93,
          name: 'Seated Dip',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.push,
        ),

// cardio
        Exercise(
          id: 94,
          name: 'Treadmill',
          exerciseType: ExerciseType.cardio,
          muscleGroup: MuscleGroup.other,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.other,
        ),
        Exercise(
          id: 95,
          name: 'Cross Trainer',
          exerciseType: ExerciseType.cardio,
          muscleGroup: MuscleGroup.other,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.other,
        ),
        Exercise(
          id: 96,
          name: 'Rowing Machine',
          exerciseType: ExerciseType.cardio,
          muscleGroup: MuscleGroup.other,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.other,
        ),
        Exercise(
          id: 97,
          name: 'Stair Climber',
          exerciseType: ExerciseType.cardio,
          muscleGroup: MuscleGroup.other,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.other,
        ),
        Exercise(
          id: 98,
          name: 'Seated Bicycle',
          exerciseType: ExerciseType.cardio,
          muscleGroup: MuscleGroup.other,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.other,
        ),

// additions

        Exercise(
          id: 99,
          name: 'Tricep Bar Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
        ),
        Exercise(
          id: 100,
          name: 'Lateral Raise Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.push,
        ),
        Exercise(
          id: 101,
          name: 'Low Row Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
        ),
        Exercise(
          id: 102,
          name: 'Single Lat Pulldown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
        ),
      ];
}
