import 'package:gymvision/db/classes/flavour_text.dart';
import 'package:gymvision/enums.dart';

import '../db/classes/exercise.dart';

class DataHelper {
  static List<FlavourText> getFlavourTests() => [
        FlavourText(message: "Make sure you are drinking enough water!"),
        FlavourText(message: "Rest days are as important as workout days!"),
        FlavourText(message: "Giving up kills gains!"),
        FlavourText(message: "Remember to warm-up and cool-down!"),
        FlavourText(message: "Even the smallest workouts help you grow!"),
        FlavourText(message: "Mindset is half of the struggle!"),
        FlavourText(message: "Your limits arent real. Only in the mind"),
        FlavourText(message: "Have a good workout!"),
        FlavourText(message: "Routine is the best form of discipline!"),
        FlavourText(message: "Be extra careful when hitting PRs!"),
        FlavourText(message: "If you keep showing up, you'll be unbeatable!"),
      ];

  static List<Exercise> getDefaultExercises() => [
// shoulders
        Exercise(
          name: 'DB Shoulder Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Steering Wheel Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'DB Side Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Front Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Rear Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Side Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Front Delt Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Rear Delt Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable External Rotation',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Barbell Shoulder Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.barbell,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Plated Shoulder Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Shoulder Press Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.shoulders,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.push,
          isDouble: false,
        ),

// chest
        Exercise(
          name: 'Plated Chest Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Low Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Mid Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable High Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Fly',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Flat Chest Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Incline Chest Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Flat Bench Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Incline Bench Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Pectoral Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.chest,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.push,
          isDouble: false,
        ),

// biceps
        Exercise(
          name: 'DB Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Seated DB Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Barbell Bicep Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.barbell,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Cable Bar Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Cable Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Hammer Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Chin Up',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Preacher Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.biceps,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),

// back
        Exercise(
          name: 'DB Shrug',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Barbell Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Cable Diverging Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Pullover',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Cable Single Pullover',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Lat Pulldown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Short Grip Lat Pulldown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Seated Low Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Plated Low Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'T Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Bench DB Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Pull up',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Kneeling Cable Row',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.back,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),

// triceps
        Exercise(
          name: 'Triceps Pushdown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Tricep Pushdown',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Triceps Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Cable Tricep Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Triceps Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Single DB Tricep Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.push,
          isDouble: true,
        ),
        Exercise(
          name: 'Triceps Dip',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.push,
          isDouble: false,
        ),
        Exercise(
          name: 'Skull Crushers',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.triceps,
          equipment: ExerciseEquipment.barbell,
          split: ExerciseSplit.push,
          isDouble: false,
        ),

// core
        Exercise(
          name: 'Crunch Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Suspended Leg Lifts',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.bodyWeight,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Oblique Lift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.kettlebell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Sit-Ups',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Russian Twists',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
        Exercise(
          name: 'Cable Crunch',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.core,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),

// hamstrings & glutes
        Exercise(
          name: 'Cable Abductor Lift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Abductor Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Seated Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Seated Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Prone Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Prone Leg Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Sumo Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Deadlift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Sumo Deadlift',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'RDL',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'DB RDL',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Hip Thrust',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.hamstringsAndGlutes,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),

// quads & calves
        Exercise(
          name: 'Hack Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Squat',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Barbell Lunge',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'DB Lunge',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Leg Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Calf Press',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Leg Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Leg Extension',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Barbell Calf Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),
        Exercise(
          name: 'Single Barbell Calf Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Calf Raise',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.plates,
          split: ExerciseSplit.legs,
          isDouble: true,
        ),
        Exercise(
          name: 'Adductor Machine',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.quadsAndCalves,
          equipment: ExerciseEquipment.machine,
          split: ExerciseSplit.legs,
          isDouble: false,
        ),

// forearms
        Exercise(
          name: 'DB Wrist Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.forearms,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'DB Wrist Rotation',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.forearms,
          equipment: ExerciseEquipment.dumbbell,
          split: ExerciseSplit.pull,
          isDouble: true,
        ),
        Exercise(
          name: 'Cable Wrist Curl',
          exerciseType: ExerciseType.weight,
          muscleGroup: MuscleGroup.forearms,
          equipment: ExerciseEquipment.cable,
          split: ExerciseSplit.pull,
          isDouble: false,
        ),
      ];
}
