name: gymvision
description: An easy-to-use gym tracking app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
version: 1.0.11+50

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  collection: ^1.16.0
  easy_dynamic_theme: ^2.2.0
  dotted_border: ^2.0.0+3
  sticky_headers: ^0.3.0+2
  reorderables: ^0.6.0
  path_provider: ^2.1.5
  flutter_speed_dial: ^7.0.0
  sentry_flutter: ^8.14.2
  http: ^1.3.0
  uuid: ^4.5.1
  smooth_page_indicator: ^1.2.1
  provider: ^6.1.5
  flutter_confetti: ^0.5.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env